### ISSUE TITLE
Usage of the grammars map?

### ISSUE THREAD

**Issue by epatpol** [NeekSandhu/monaco-editor-textmate#1]
I just quickly looked at the code, but what is the use case for the grammars map? Is it to have different extension names that could use the same grammar? Could it be optional?

```typescript
    const grammars = new Map()
    grammars.set('css', 'CSS')

    await wireTmGrammars(monaco, registry, grammars)
```

**Comment by NeekSandhu** [comment]
My bad; https://github.com/NeekSandhu/monaco-editor-textmate/commit/74267f02740bc492d848f967432e89575fb97722 should explain why you need that map.

The human readable `keys` or language names are used by `monaco-editor` to set language ID's, and not so human readable `values` are used by TextMate engine.

**Comment by epatpol** [comment]
Thanks!
