### ISSUE TITLE
Update to the newest monaco-editor-version

### ISSUE THREAD

**Issue by NLueg** [NeekSandhu/monaco-editor-textmate#10]
Would it be possible to update to the newest monaco-editor version?
I always receive an npm-warning in my project because I use the newest version and this library needs monaco `0.14.0`.

**Comment by NeekSandhu** [comment]
Yes, of course :)

Will do within next 24 hours and post here.

**Comment by NLueg** [comment]
Awesome, thank you for your fast response!

**Comment by NLueg** [comment]
I tried the new version and everything is fine now.
Thank you for the fast update!
