### ISSUE TITLE
⚠ Parsing long text lines can consume a lot of CPU resources!

### ISSUE THREAD

**Issue by SuperManito** [NeekSandhu/monaco-editor-textmate#29]
Editor option [maxTokenizationLineLength](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlobalEditorOptions.html#maxTokenizationLineLength) is not work. Parsing long text lines can consume a lot of CPU resources, leading to browser page fake death. Under normal circumstances, long text lines should not be parsed.

**Comment by xueerli** [comment]
@SuperManito How did you solve it?

**Comment by SuperManito** [comment]
> @SuperManito How did you solve it?

https://github.com/shikijs/shiki 了解一下，你会发现一个新大陆，这个项目问题太多并且已经不活跃了

**Comment by XiayidanAlimu** [comment]
> > @SuperManito How did you solve it?
> 
> [shikijs/shiki](https://github.com/shikijs/shiki) 了解一下，你会发现一个新大陆，这个项目问题太多并且已经不活跃了

我也遇到解析长代码时，网页崩溃的情况，发现就是在使用monaco-editor-textmate之后，解析代码实现高亮效果时，耗时最长导致的。也看了一下午shikijs/shiki，看到他有专门的monaco集成案例，你也是用在vue项目吗? 我这里vue2环境依赖安装和使用都碰到问题

**Comment by SuperManito** [comment]
> > > @SuperManito How did you solve it?
> > 
> > 
> > [shikijs/shiki](https://github.com/shikijs/shiki) 了解一下，你会发现一个新大陆，这个项目问题太多并且已经不活跃了
> 
> 我也遇到解析长代码时，网页崩溃的情况，发现就是在使用monaco-editor-textmate之后，解析代码实现高亮效果时，耗时最长导致的。也看了一下午shikijs/shiki，看到他有专门的monaco集成案例，你也是用在vue项目吗? 我这里vue2环境依赖安装和使用都碰到问题

是的，这是我的开源项目 https://github.com/SuperManito/Arcadia

坑基本上都踩过一遍了，首先这摩纳哥编辑器就是个大坑，体积太大、bug多、优化差，没有平替没办法

**Comment by XiayidanAlimu** [comment]
> > > > @SuperManito How did you solve it?
> > > 
> > > 
> > > [shikijs/shiki](https://github.com/shikijs/shiki) 了解一下，你会发现一个新大陆，这个项目问题太多并且已经不活跃了
> > 
> > 
> > 我也遇到解析长代码时，网页崩溃的情况，发现就是在使用monaco-editor-textmate之后，解析代码实现高亮效果时，耗时最长导致的。也看了一下午shikijs/shiki，看到他有专门的monaco集成案例，你也是用在vue项目吗? 我这里vue2环境依赖安装和使用都碰到问题
> 
> 是的，这是我的开源项目 [SuperManito/Arcadia](https://github.com/SuperManito/Arcadia)
> 
> 坑基本上都踩过一遍了，首先这摩纳哥编辑器就是个大坑，体积太大、bug多、优化差，没有平替没办法

是的，我们之前从code-mirror迁移到monaco-editor，用了快两年，今天被提出这个性能问题，项目做的好厉害，但是我在你项目里也没有看到用shikijs或monaco唉

**Comment by SuperManito** [comment]
> > > > > @SuperManito How did you solve it?
> > > > 
> > > > 
> > > > [shikijs/shiki](https://github.com/shikijs/shiki) 了解一下，你会发现一个新大陆，这个项目问题太多并且已经不活跃了
> > > 
> > > 
> > > 我也遇到解析长代码时，网页崩溃的情况，发现就是在使用monaco-editor-textmate之后，解析代码实现高亮效果时，耗时最长导致的。也看了一下午shikijs/shiki，看到他有专门的monaco集成案例，你也是用在vue项目吗? 我这里vue2环境依赖安装和使用都碰到问题
> > 
> > 
> > 是的，这是我的开源项目 [SuperManito/Arcadia](https://github.com/SuperManito/Arcadia)
> > 坑基本上都踩过一遍了，首先这摩纳哥编辑器就是个大坑，体积太大、bug多、优化差，没有平替没办法
> 
> 是的，我们之前从code-mirror迁移到monaco-editor，用了快两年，今天被提出这个性能问题，项目做的好厉害，但是我在你项目里也没有看到用shikijs或monaco唉

我项目前端是闭源的你肯定看不到
