### ISSUE TITLE
Export TokenizerState class

### ISSUE THREAD

**Issue by marechal-p** [NeekSandhu/monaco-editor-textmate#4]
I don't know if it is such a good idea, but I was trying to define my own tokenizer using your package, but the `TokenizerState` class is not exported. I was just hoping I could import it instead of having to write something that would do exactly what you already did :)

(I don't know how the copyrights would play here, so I would prefer having you exporting the class)

**Comment by NeekSandhu** [comment]
Will do certainly.

Expect a patch later today

**Comment by NeekSandhu** [comment]
I saw one of your pull requests in theia repo where had a workaround. Is this still necessary?

**Comment by marechal-p** [comment]
I made a workaround indeed, doesn't mean this wouldn't benefit someone though :)

**Comment by NeekSandhu** [comment]
Hopefully `monaco-editor` adds support for scopeName arrays soon, then `monaco-editor-textmate` will work out of the box anyway; without additional hacking.

___

Consider bumping https://github.com/Microsoft/monaco-editor/issues/929

_cc Theia contributors @marechal-p @epatpol @svenefftinge @mofux_
